//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerouteSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectEntitiesAfterAdd {
            get {
                return ((bool)(this["SelectEntitiesAfterAdd"]));
            }
            set {
                this["SelectEntitiesAfterAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Grayscale {
            get {
                return ((bool)(this["Grayscale"]));
            }
            set {
                this["Grayscale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float Lambda {
            get {
                return ((float)(this["Lambda"]));
            }
            set {
                this["Lambda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll0 {
            get {
                return ((bool)(this["LockScroll0"]));
            }
            set {
                this["LockScroll0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll1 {
            get {
                return ((bool)(this["LockScroll1"]));
            }
            set {
                this["LockScroll1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll2 {
            get {
                return ((bool)(this["LockScroll2"]));
            }
            set {
                this["LockScroll2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom0 {
            get {
                return ((bool)(this["LockZoom0"]));
            }
            set {
                this["LockZoom0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom1 {
            get {
                return ((bool)(this["LockZoom1"]));
            }
            set {
                this["LockZoom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom2 {
            get {
                return ((bool)(this["LockZoom2"]));
            }
            set {
                this["LockZoom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideGrid {
            get {
                return ((bool)(this["HideGrid"]));
            }
            set {
                this["HideGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideLambdaMetrics {
            get {
                return ((bool)(this["HideLambdaMetrics"]));
            }
            set {
                this["HideLambdaMetrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellTextAlignment {
            get {
                return ((int)(this["CellTextAlignment"]));
            }
            set {
                this["CellTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ViasTextAlignment {
            get {
                return ((int)(this["ViasTextAlignment"]));
            }
            set {
                this["ViasTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WireTextAlignment {
            get {
                return ((int)(this["WireTextAlignment"]));
            }
            set {
                this["WireTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SelectionBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectionBoxColor"]));
            }
            set {
                this["SelectionBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ViasInputColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasInputColor"]));
            }
            set {
                this["ViasInputColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ViasOutputColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasOutputColor"]));
            }
            set {
                this["ViasOutputColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ViasInoutColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasInoutColor"]));
            }
            set {
                this["ViasInoutColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViasConnectColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasConnectColor"]));
            }
            set {
                this["ViasConnectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ViasFloatingColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasFloatingColor"]));
            }
            set {
                this["ViasFloatingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViasPowerColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasPowerColor"]));
            }
            set {
                this["ViasPowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViasGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasGroundColor"]));
            }
            set {
                this["ViasGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color WireInterconnectColor {
            get {
                return ((global::System.Drawing.Color)(this["WireInterconnectColor"]));
            }
            set {
                this["WireInterconnectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color WirePowerColor {
            get {
                return ((global::System.Drawing.Color)(this["WirePowerColor"]));
            }
            set {
                this["WirePowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color WireGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["WireGroundColor"]));
            }
            set {
                this["WireGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color CellNotColor {
            get {
                return ((global::System.Drawing.Color)(this["CellNotColor"]));
            }
            set {
                this["CellNotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color CellBufferColor {
            get {
                return ((global::System.Drawing.Color)(this["CellBufferColor"]));
            }
            set {
                this["CellBufferColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color CellMuxColor {
            get {
                return ((global::System.Drawing.Color)(this["CellMuxColor"]));
            }
            set {
                this["CellMuxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color CellLogicColor {
            get {
                return ((global::System.Drawing.Color)(this["CellLogicColor"]));
            }
            set {
                this["CellLogicColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CellAdderColor {
            get {
                return ((global::System.Drawing.Color)(this["CellAdderColor"]));
            }
            set {
                this["CellAdderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color CellBusSuppColor {
            get {
                return ((global::System.Drawing.Color)(this["CellBusSuppColor"]));
            }
            set {
                this["CellBusSuppColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color CellFlipFlopColor {
            get {
                return ((global::System.Drawing.Color)(this["CellFlipFlopColor"]));
            }
            set {
                this["CellFlipFlopColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color CellLatchColor {
            get {
                return ((global::System.Drawing.Color)(this["CellLatchColor"]));
            }
            set {
                this["CellLatchColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snow")]
        public global::System.Drawing.Color CellOtherColor {
            get {
                return ((global::System.Drawing.Color)(this["CellOtherColor"]));
            }
            set {
                this["CellOtherColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snow")]
        public global::System.Drawing.Color UnitRegfileColor {
            get {
                return ((global::System.Drawing.Color)(this["UnitRegfileColor"]));
            }
            set {
                this["UnitRegfileColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snow")]
        public global::System.Drawing.Color UnitMemoryColor {
            get {
                return ((global::System.Drawing.Color)(this["UnitMemoryColor"]));
            }
            set {
                this["UnitMemoryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snow")]
        public global::System.Drawing.Color UnitCustomColor {
            get {
                return ((global::System.Drawing.Color)(this["UnitCustomColor"]));
            }
            set {
                this["UnitCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color SelectionColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectionColor"]));
            }
            set {
                this["SelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ViasOverrideColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasOverrideColor"]));
            }
            set {
                this["ViasOverrideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WireOverrideColor {
            get {
                return ((global::System.Drawing.Color)(this["WireOverrideColor"]));
            }
            set {
                this["WireOverrideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CellOverrideColor {
            get {
                return ((global::System.Drawing.Color)(this["CellOverrideColor"]));
            }
            set {
                this["CellOverrideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RegionOverrideColor {
            get {
                return ((global::System.Drawing.Color)(this["RegionOverrideColor"]));
            }
            set {
                this["RegionOverrideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ViasPriority {
            get {
                return ((int)(this["ViasPriority"]));
            }
            set {
                this["ViasPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WirePriority {
            get {
                return ((int)(this["WirePriority"]));
            }
            set {
                this["WirePriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CellPriority {
            get {
                return ((int)(this["CellPriority"]));
            }
            set {
                this["CellPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int BeaconPriority {
            get {
                return ((int)(this["BeaconPriority"]));
            }
            set {
                this["BeaconPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RegionPriority {
            get {
                return ((int)(this["RegionPriority"]));
            }
            set {
                this["RegionPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPriority {
            get {
                return ((bool)(this["AutoPriority"]));
            }
            set {
                this["AutoPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int ViasOpacity {
            get {
                return ((int)(this["ViasOpacity"]));
            }
            set {
                this["ViasOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int WireOpacity {
            get {
                return ((int)(this["WireOpacity"]));
            }
            set {
                this["WireOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int CellOpacity {
            get {
                return ((int)(this["CellOpacity"]));
            }
            set {
                this["CellOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ViasBaseSize {
            get {
                return ((int)(this["ViasBaseSize"]));
            }
            set {
                this["ViasBaseSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int WireBaseSize {
            get {
                return ((int)(this["WireBaseSize"]));
            }
            set {
                this["WireBaseSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ViasShape {
            get {
                return ((int)(this["ViasShape"]));
            }
            set {
                this["ViasShape"] = value;
            }
        }
    }
}
