//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerouteSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectEntitiesAfterAdd {
            get {
                return ((bool)(this["SelectEntitiesAfterAdd"]));
            }
            set {
                this["SelectEntitiesAfterAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Grayscale {
            get {
                return ((bool)(this["Grayscale"]));
            }
            set {
                this["Grayscale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float Lambda {
            get {
                return ((float)(this["Lambda"]));
            }
            set {
                this["Lambda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll0 {
            get {
                return ((bool)(this["LockScroll0"]));
            }
            set {
                this["LockScroll0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll1 {
            get {
                return ((bool)(this["LockScroll1"]));
            }
            set {
                this["LockScroll1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockScroll2 {
            get {
                return ((bool)(this["LockScroll2"]));
            }
            set {
                this["LockScroll2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom0 {
            get {
                return ((bool)(this["LockZoom0"]));
            }
            set {
                this["LockZoom0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom1 {
            get {
                return ((bool)(this["LockZoom1"]));
            }
            set {
                this["LockZoom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockZoom2 {
            get {
                return ((bool)(this["LockZoom2"]));
            }
            set {
                this["LockZoom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideGrid {
            get {
                return ((bool)(this["HideGrid"]));
            }
            set {
                this["HideGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideLambdaMetrics {
            get {
                return ((bool)(this["HideLambdaMetrics"]));
            }
            set {
                this["HideLambdaMetrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellTextAlignment {
            get {
                return ((int)(this["CellTextAlignment"]));
            }
            set {
                this["CellTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ViasTextAlignment {
            get {
                return ((int)(this["ViasTextAlignment"]));
            }
            set {
                this["ViasTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WireTextAlignment {
            get {
                return ((int)(this["WireTextAlignment"]));
            }
            set {
                this["WireTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SelectionBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectionBoxColor"]));
            }
            set {
                this["SelectionBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ViasInputColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasInputColor"]));
            }
            set {
                this["ViasInputColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasOutputColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasOutputColor"]));
            }
            set {
                this["ViasOutputColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasInoutColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasInoutColor"]));
            }
            set {
                this["ViasInoutColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasConnectColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasConnectColor"]));
            }
            set {
                this["ViasConnectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasFloatingColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasFloatingColor"]));
            }
            set {
                this["ViasFloatingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasPowerColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasPowerColor"]));
            }
            set {
                this["ViasPowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViasGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ViasGroundColor"]));
            }
            set {
                this["ViasGroundColor"] = value;
            }
        }
    }
}
